"""initial backend schema

Revision ID: 79b0c52c188e
Revises: 
Create Date: 2026-08-04 13:35:17.838119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '79b0c52c188e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_number', sa.String(length=32), nullable=False),
    sa.Column('enterprise_number', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_number')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_branch_number'), ['branch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_enterprise_number'), ['enterprise_number'], unique=False)

    op.create_table('code_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'code', 'language')
    )
    with op.batch_alter_table('code_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_references_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_references_code'), ['code'], unique=False)

    op.create_table('denominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_number', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('denomination_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_number', 'language', 'denomination_type', 'value')
    )
    with op.batch_alter_table('denominations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_denominations_entity_number'), ['entity_number'], unique=False)

    op.create_table('import_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('import_type', sa.String(length=16), nullable=False),
    sa.Column('source_date', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_audits_source_checksum'), ['source_checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_audits_status'), ['status'], unique=False)

    op.create_table('kbo_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_number', sa.String(length=32), nullable=False),
    sa.Column('address_type', sa.String(length=32), nullable=False),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('house_number', sa.String(length=32), nullable=True),
    sa.Column('box', sa.String(length=32), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('municipality', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_number', 'address_type')
    )
    with op.batch_alter_table('kbo_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kbo_addresses_entity_number'), ['entity_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_kbo_addresses_postcode'), ['postcode'], unique=False)

    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=256), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_identifier', 'target_type', 'target_id')
    )
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_candidates_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_source_identifier'), ['source_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_target_id'), ['target_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_number', sa.String(length=32), nullable=False),
    sa.Column('official_name', sa.String(length=512), nullable=False),
    sa.Column('legal_form', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('is_natural_person', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_enterprise_number'), ['enterprise_number'], unique=True)

    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_jobs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_jobs_queue'), ['queue'], unique=False)

    op.create_table('suppressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_number', sa.String(length=32), nullable=True),
    sa.Column('establishment_number', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('telephone', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('requested_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressions_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppressions_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppressions_enterprise_number'), ['enterprise_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppressions_establishment_number'), ['establishment_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppressions_telephone'), ['telephone'], unique=False)

    op.create_table('entity_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=256), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('match_candidate_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_candidate_id'], ['match_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_identifier', 'target_type')
    )
    with op.batch_alter_table('entity_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_links_source_identifier'), ['source_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_links_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_links_target_id'), ['target_id'], unique=False)

    op.create_table('establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('establishment_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('house_number', sa.String(length=32), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('municipality', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_confidence', sa.Float(), nullable=True),
    sa.Column('geo_source', sa.String(length=64), nullable=True),
    sa.Column('geo_updated_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('preliminary_score', sa.Float(), nullable=False),
    sa.Column('segment_hint', sa.String(length=64), nullable=True),
    sa.Column('enrichment_stage', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_establishments_establishment_number'), ['establishment_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_establishments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_establishments_postcode'), ['postcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_establishments_region'), ['region'], unique=False)

    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('source_identifier', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('source_updated_at', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('import_audit_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['import_audit_id'], ['import_audits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_identifier', 'entity_type', 'checksum')
    )
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_records_import_audit_id'), ['import_audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_records_source_identifier'), ['source_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_records_source_name'), ['source_name'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('nace_version', sa.String(length=16), nullable=False),
    sa.Column('nace_code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('source_date', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('establishment_id', 'nace_code', 'nace_version')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_establishment_id'), ['establishment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_nace_code'), ['nace_code'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=True),
    sa.Column('contact_type', sa.String(length=32), nullable=False),
    sa.Column('contact_value', sa.String(length=512), nullable=False),
    sa.Column('generic_business_contact', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('verification_provider', sa.String(length=64), nullable=True),
    sa.Column('verification_detail', sa.Text(), nullable=True),
    sa.Column('lawful_basis', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_verification_state'), ['verification_state'], unique=False)

    op.create_table('cost_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('estimated_cost_eur', sa.Float(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('data_fresh_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_events_correlation_id'), ['correlation_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('establishment_id', sa.Integer(), nullable=True),
    sa.Column('feature_name', sa.String(length=128), nullable=False),
    sa.Column('feature_value', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_date', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('entity_match_confidence', sa.Float(), nullable=False),
    sa.Column('freshness_factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_establishment_id'), ['establishment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_feature_name'), ['feature_name'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('establishment_id', sa.Integer(), nullable=True),
    sa.Column('feature_name', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_establishment_id'), ['establishment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_feature_name'), ['feature_name'], unique=False)

    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('lawful_basis', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_establishment_id'), ['establishment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_events_event_type'), ['event_type'], unique=False)

    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('timing_score', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('strategic_score', sa.Float(), nullable=False),
    sa.Column('expected_deal_value_eur', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('score_components_json', sa.JSON(), nullable=False),
    sa.Column('explainable_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('human_feedback', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_scores_establishment_id'), ['establishment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_scores_organization_id'), ['organization_id'], unique=False)

    op.create_table('review_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establishment_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('lawful_basis', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_actions_establishment_id'), ['establishment_id'], unique=False)

    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('establishment_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('crawl_status', sa.String(length=32), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_websites_establishment_id'), ['establishment_id'], unique=False)

    op.create_table('machine_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_score_id', sa.Integer(), nullable=False),
    sa.Column('primary_machine', sa.String(length=64), nullable=False),
    sa.Column('alternative_machines_json', sa.JSON(), nullable=False),
    sa.Column('required_features_json', sa.JSON(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('questions_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['lead_score_id'], ['lead_scores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_score_id')
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
        op.execute(
            "ALTER TABLE establishments "
            "ADD COLUMN location geometry(Point, 4326)"
        )
        op.execute(
            "CREATE INDEX ix_establishments_location_gist "
            "ON establishments USING GIST (location)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_establishments_location_gist")
        op.execute("ALTER TABLE establishments DROP COLUMN IF EXISTS location")
    op.drop_table('machine_recommendations')
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_websites_establishment_id'))

    op.drop_table('websites')
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_actions_establishment_id'))

    op.drop_table('review_actions')
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_scores_organization_id'))
        batch_op.drop_index(batch_op.f('ix_lead_scores_establishment_id'))

    op.drop_table('lead_scores')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_feedback_events_establishment_id'))

    op.drop_table('feedback_events')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_feature_name'))
        batch_op.drop_index(batch_op.f('ix_features_establishment_id'))

    op.drop_table('features')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_feature_name'))
        batch_op.drop_index(batch_op.f('ix_evidence_establishment_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('cost_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_events_correlation_id'))

    op.drop_table('cost_events')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_verification_state'))
        batch_op.drop_index(batch_op.f('ix_contacts_organization_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_nace_code'))
        batch_op.drop_index(batch_op.f('ix_activities_establishment_id'))

    op.drop_table('activities')
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_records_source_name'))
        batch_op.drop_index(batch_op.f('ix_source_records_source_identifier'))
        batch_op.drop_index(batch_op.f('ix_source_records_import_audit_id'))

    op.drop_table('source_records')
    with op.batch_alter_table('establishments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_establishments_region'))
        batch_op.drop_index(batch_op.f('ix_establishments_postcode'))
        batch_op.drop_index(batch_op.f('ix_establishments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_establishments_establishment_number'))

    op.drop_table('establishments')
    with op.batch_alter_table('entity_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_links_target_id'))
        batch_op.drop_index(batch_op.f('ix_entity_links_source_type'))
        batch_op.drop_index(batch_op.f('ix_entity_links_source_identifier'))

    op.drop_table('entity_links')
    with op.batch_alter_table('suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressions_telephone'))
        batch_op.drop_index(batch_op.f('ix_suppressions_establishment_number'))
        batch_op.drop_index(batch_op.f('ix_suppressions_enterprise_number'))
        batch_op.drop_index(batch_op.f('ix_suppressions_email'))
        batch_op.drop_index(batch_op.f('ix_suppressions_domain'))

    op.drop_table('suppressions')
    with op.batch_alter_table('processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_jobs_queue'))
        batch_op.drop_index(batch_op.f('ix_processing_jobs_correlation_id'))

    op.drop_table('processing_jobs')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_enterprise_number'))

    op.drop_table('organizations')
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_candidates_target_id'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_source_type'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_source_identifier'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_decision'))

    op.drop_table('match_candidates')
    with op.batch_alter_table('kbo_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kbo_addresses_postcode'))
        batch_op.drop_index(batch_op.f('ix_kbo_addresses_entity_number'))

    op.drop_table('kbo_addresses')
    with op.batch_alter_table('import_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_audits_status'))
        batch_op.drop_index(batch_op.f('ix_import_audits_source_checksum'))

    op.drop_table('import_audits')
    with op.batch_alter_table('denominations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_denominations_entity_number'))

    op.drop_table('denominations')
    with op.batch_alter_table('code_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_references_code'))
        batch_op.drop_index(batch_op.f('ix_code_references_category'))

    op.drop_table('code_references')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_enterprise_number'))
        batch_op.drop_index(batch_op.f('ix_branches_branch_number'))

    op.drop_table('branches')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_correlation_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
